### ISSUE TITLE
CK error: [package] package installation failed!

### ISSUE THREAD

**Issue by Srivathsav-max** [ctuning/ck-mlops#4]
ck install package --tags=lib,armnn,tflite,neon,opencl,rel.20.08

More than one package or version found:

 0) lib-armnn (f517b24b03b2b61f), Variations: rel.20.08,tflite,neon,opencl
 1) lib-armnn (f517b24b03b2b61f), Variations: rel.20.08,tflite,neon,opencl
 2) lib-armnn (f517b24b03b2b61f), Variations: rel.20.08,tflite,neon,opencl

Please select the package to install [ hit return for "0" ]: 0

  Package found: lib-armnn (f517b24b03b2b61f)

  -----------------------------------
  Resolving software dependencies ...

*** Dependency 1 = lib-boost (Boost library):

 ********
 WARNING: no registered CK environment was found for "Boost library" dependency with tags="lib,boost,for-armnn" and setup={"host_os_uoa": "linux-64", "target_os_uoa": "linux-64", "target_os_bits": "64"} and version constraints ([1, 64, 0] <= v <= [1, 66, 0])

  Searching and installing CK software packages ...
    * tags:        lib,boost,for-armnn
    * or tags:
    * no tags:

More than one package or version found:

 0) lib-boost-1.66.0  Version 1.66.0  (0417ba98aa5ca4ad), Variations: for-armnn
 1) lib-boost-1.66.0  Version 1.66.0  (0417ba98aa5ca4ad), Variations: for-armnn
 2) lib-boost-1.66.0  Version 1.66.0  (0417ba98aa5ca4ad), Variations: for-armnn
 3) lib-boost-1.65.1  Version 1.65.1  (8bb8a5b19b48120c), Variations: for-armnn
 4) lib-boost-1.65.1  Version 1.65.1  (8bb8a5b19b48120c), Variations: for-armnn
 5) lib-boost-1.65.1  Version 1.65.1  (8bb8a5b19b48120c), Variations: for-armnn
 6) lib-boost-1.64.0  Version 1.64.0  (c6a6991d5c951d20), Variations: for-armnn
 7) lib-boost-1.64.0  Version 1.64.0  (c6a6991d5c951d20), Variations: for-armnn
 8) lib-boost-1.64.0  Version 1.64.0  (c6a6991d5c951d20), Variations: for-armnn

Please select the package to install [ hit return for "0" ]: 0

  Package found: lib-boost-1.66.0 (0417ba98aa5ca4ad)

  -----------------------------------
  Resolving software dependencies ...

*** Dependency 1 = cmake (cmake):

    Resolved. CK environment UID = b269ae509c47a2a7 (detected version 3.14.3)

*** Dependency 2 = compiler (C++ compiler):

More than one environment found for "C++ compiler" with tags="compiler,lang-cpp" and setup={"host_os_uoa": "linux-64", "target_os_uoa": "linux-64", "target_os_bits": "64"}:

 0) GNU C compiler - v9.3.0 (64bits,compiler,gcc,host-os-linux-64,lang-c,lang-cpp,target-os-linux-64,v9,v9.3,v9.3.0 (093326cb3ccb990f))

 1) LLVM compiler - v10.0.0-4ubuntu1 (64bits,compiler,host-os-linux-64,lang-c,lang-cpp,llvm,target-os-linux-64,v10,v10.0,v10.0.0,v10.0.0.0 (0688b7d5dc0fa909))

Select one of the options for "C++ compiler" with tags="compiler,lang-cpp" and setup={"host_os_uoa": "linux-64", "target_os_uoa": "linux-64", "target_os_bits": "64"} [ hit return for "0" ]: 0

    Resolved. CK environment UID = 093326cb3ccb990f (detected version 9.3.0)
  -----------------------------------

Searching if CK environment for this package already exists using:
  * Tags: compiled-by-gcc,compiled-by-gcc-9.3.0,lib,boost,v1.66.0,v1.66,v1,channel-stable,for-armnn,host-os-linux-64,target-os-linux-64,64bits
  * Dependency: cmake=b269ae509c47a2a7
  * Dependency: compiler=093326cb3ccb990f

CK environment not found for this package ...

*** Installation path used: /root/CK-TOOLS/lib-boost-1.66.0-gcc-9.3.0-for-armnn-linux-64

  -----------------------------------
  Resolving software dependencies ...

*** Dependency 1 = cmake (cmake):

    Resolved. CK environment UID = b269ae509c47a2a7 (detected version 3.14.3)

*** Dependency 2 = compiler (C++ compiler):

    Resolved. CK environment UID = 093326cb3ccb990f (detected version 9.3.0)
  -----------------------------------

Installing to /root/CK-TOOLS/lib-boost-1.66.0-gcc-9.3.0-for-armnn-linux-64

Using scripts from /root/CK/mlcommons@ck-mlops/package/lib-boost-1.62.0

Downloading package from 'https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.zip' ...
--2021-12-08 11:19:17--  https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.zip
Resolving dl.bintray.com (dl.bintray.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘dl.bintray.com’
Error: downloading package failed!

   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   CK detected a PROBLEM in the third-party CK package:

   CK package:           lib-boost-1.66.0
   Native package URL:   https://dl.bintray.com/boostorg/release/1.66.0/source
   CK repo:              mlcommons@ck-mlops

   CK repo URL:          https://github.com/mlcommons/ck-mlops
   CK package URL:       https://github.com/mlcommons/ck-mlops/tree/master/package/lib-boost-1.66.0

   CodeReef stable package URL: https://cKnowledge.io/c/package/lib-boost-1.66.0
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Please, submit the *full* log to the authors of this external CK package
   at https://github.com/mlcommons/ck-mlops/issues to collaboratively fix this problem!

CK error: [package] package installation failed!

Unable to install a version of boost library

**Comment by gfursin** [comment]
Hi @Srivathsav-max.

Thank you for reporting this issue and sorry for the delay in replying - we were very busy with TVMCon.

It seems that Boost developers moved all their packages from bintray to jfrog artifactory:
* https://boostorg.jfrog.io/artifactory/main/release/1.66.0/source

We will need to update the meta.json for CK boost package to reflect these changes:
* https://github.com/mlcommons/ck-mlops/blob/main/package/lib-boost-1.66.0/.cm/meta.json

CC @hanwenzhu @arjunsuresh .

**Comment by gfursin** [comment]
Many thanks to @arjunsuresh for fixing the URLs: https://github.com/mlcommons/ck-mlops/pull/6

@Srivathsav-max - can you please update this repo:
```
ck pull repo:mlcommons@ck-mlops
```
and try again?

Thanks!

**Comment by Srivathsav-max** [comment]
patching file tensorflow/lite/tools/make/download_dependencies.sh
--------------------------------
Download dependencies ...

downloading https://mirror.bazel.build/bitbucket.org/eigen/eigen/get/9f48e814419e.tar.gz
downloading https://mirror.bazel.build/github.com/google/gemmlowp/archive/38ebac7b059e84692f53e5938f97a9943c120d98.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  895k  100  895k    0     0  5234k      0 --:--:-- --:--:-- --:--:-- 5234k
/home/samsung/CK-TOOLS/lib-tflite-src-static-1.13.1-gcc-9.3.0-linux-64/src/tensorflow/lite/tools/make/download_dependencies.sh: line 70: unzip: command not found

   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   CK detected a PROBLEM in the third-party CK package:

   CK package:           lib-tflite-1.13.1-src-static
   Native package URL:   https://github.com/tensorflow/tensorflow
   Git checkout:         v1.13.1
   CK repo:              mlcommons@ck-mlops
   CK repo URL:          https://github.com/mlcommons/ck-mlops
   CK package URL:       https://github.com/mlcommons/ck-mlops/tree/master/package/lib-tflite-1.13.1-src-static
   Issues URL:           https://github.com/mlcommons/ck-mlops/issues

   CK stable package URL: https://cKnowledge.io/c/package/lib-tflite-1.13.1-src-static

   Please, check that there is no discussion about this issue at https://cKnowledge.io/c/package/lib-tflite-1.13.1-src-static

   Please, submit the original comand line and the *full* log to:
     * https://github.com/ctuning/ck/issues
     * https://github.com/ctuning/ck-mlops/issues
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CK error: [package] package installation failed!

**Comment by Srivathsav-max** [comment]
Again I Failed While Downloading The Dependencies

**Comment by arjunsuresh** [comment]
```unzip: command not found``` -- You'll need to install this package on your system.

**Comment by Srivathsav-max** [comment]
> `unzip: command not found` -- You'll need to install this package on your system.

Thank you @arjunsuresh
