### ISSUE TITLE
loadgen install failed on fedora 34

### ISSUE THREAD

**Issue by bill2345** [ctuning/ck-mlops#8]
I followed this page: https://colab.research.google.com/drive/1ij1rWoqje5-Sn6UsdFj1OzYakudI2RIS?usp=sharing#scrollTo=lt7aU3scRLZ4
Please help and thanks!

##################################################################################
steps:

# Pull CK MLOps repo
ck pull repo:mlcommons@ck-mlops

# Initialize platform
ck setup kernel --var.install_to_env=yes
ck detect platform.os --platform_init_uoa=generic-linux-dummy

# Add Python, GCC, CMake to CK
ck detect soft:compiler.python --full_path={sys.executable}
ck detect soft:compiler.gcc --full_path=`which gcc`
ck detect soft:tool.cmake --full_path=`which cmake`

# Install Python dependencies
python3 -m pip install protobuf

# Download mlcommons/inference repo
ck install package --quiet --tags=mlperf,inference,src,r1.1

# Install dependencies
ck install package --tags=lib,python-package,absl
ck install package --tags=lib,python-package,numpy
ck install package --tags=lib,python-package,scipy
ck install package --tags=lib,python-package,matplotlib
ck install package --tags=lib,python-package,cython
ck install package --tags=lib,python-package,opencv-python-headless
ck install package --tags=lib,python-package,mlperf,loadgen
##################################################################################

(mlperf-inference) bash-5.1$ ck install package --tags=lib,python-package,mlperf,loadgen

  Package found: lib-python-mlperf-loadgen (6b744d888c45962b)

  -----------------------------------
  Resolving software dependencies ...

*** Dependency 1 = mlperf-inference (MLPerf Inference source):

    Resolved. CK environment UID = 7801b88d489cdd48 (version r1.1-c5b8918)

*** Dependency 2 = compiler (C++ compiler):

    Resolved. CK environment UID = 8667f4ffd932b2f9 (detected version 11.2.1)

*** Dependency 3 = python (Python interpreter):

    Resolved. CK environment UID = a84239c2f9b63d72 (detected version 3.9.12)

*** Dependency 4 = lib-python-absl (Python Abseil library):

    Resolved. CK environment UID = abf3a6e97cff1960 (version unversioned)

*** Dependency 5 = lib-python-numpy (Python NumPy library):

    Resolved. CK environment UID = 7458c1283d2f59e8 (version 1.23.0)
  -----------------------------------

Searching if CK environment for this package already exists using:
  * Tags: compiled-by-gcc,compiled-by-gcc-11.2.1,needs-python,needs-python-3.9.12,lib,python-package,mlperf,loadgen,mlperf_loadgen,mlperf-loadgen,vmaster,host-os-linux-64,target-os-linux-64,64bits
  * Dependency: mlperf-inference=7801b88d489cdd48
  * Dependency: compiler=8667f4ffd932b2f9
  * Dependency: python=a84239c2f9b63d72
  * Dependency: lib-python-absl=abf3a6e97cff1960
  * Dependency: lib-python-numpy=7458c1283d2f59e8

CK environment found for this package: 01ce5c2d548e0975

  OVERWRITING AND PROCESSING AGAIN!

  -----------------------------------
  Resolving software dependencies ...

*** Dependency 1 = mlperf-inference (MLPerf Inference source):

    Resolved. CK environment UID = 7801b88d489cdd48 (version r1.1-c5b8918)

*** Dependency 2 = compiler (C++ compiler):

    Resolved. CK environment UID = 8667f4ffd932b2f9 (detected version 11.2.1)

*** Dependency 3 = python (Python interpreter):

    Resolved. CK environment UID = a84239c2f9b63d72 (detected version 3.9.12)

*** Dependency 4 = lib-python-absl (Python Abseil library):

    Resolved. CK environment UID = abf3a6e97cff1960 (version unversioned)

*** Dependency 5 = lib-python-numpy (Python NumPy library):

    Resolved. CK environment UID = 7458c1283d2f59e8 (version 1.23.0)
  -----------------------------------

Installing to /home/wxsun/CK/local/venv/mlperf-inference/CK/local/env/01ce5c2d548e0975

**************************************************************

Cleanup: removing /home/wxsun/CK/local/venv/mlperf-inference/CK/local/env/01ce5c2d548e0975/python_deps_site
Building 'mlperf_loadgen' from source ...
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
Installing 'mlperf_loadgen' and its dependencies to '/home/wxsun/CK/local/venv/mlperf-inference/CK/local/env/01ce5c2d548e0975/python_deps_site/lib64/python3.9/site-packages' or '/home/wxsun/CK/local/venv/mlperf-inference/CK/local/env/01ce5c2d548e0975/python_deps_site/lib/python3.9/site-packages' ...
ls: cannot access 'dist/mlperf_loadgen*.whl': No such file or directory
ERROR: You must give at least one requirement to install (see "pip help install")
find: ‘/home/wxsun/CK/local/venv/mlperf-inference/CK/local/env/01ce5c2d548e0975/python_deps_site’: No such file or directory
touch: cannot touch '/__init__.py': Permission denied
Error: installation failed!

**Comment by arjunsuresh** [comment]
Hi @bill2345 , can you please try `ck clean env --tags=loadgen` and then `ck install package --tags=lib,python-package,mlperf,loadgen`? 

Meanwhile python3.9 might not build loadgen from mlperf-inference r1.1 branch. python3.7 should work with that. Alternatively you can do `ck pull all` followed by `ck install package --quiet --tags=mlperf,inference,src,r2.1` to get the latest inference repo to be used for 2.1 round of submission which works with python 3.9.

**Comment by arjunsuresh** [comment]
We are now supporting loadgen in our [CM script](https://github.com/mlcommons/ck/tree/master/cm-mlops/script/install-mlc-inference-loadgen)
